steps:
# Paso 1: Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/petparadise-api', '.']

# Paso 2: Subir la imagen al Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/petparadise-api']

# Paso 3: Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'petparadise-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/petparadise-api'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'  # Cambia la región si es necesario
    - '--allow-unauthenticated'  # Permite invocaciones no autenticadas

images:
- 'gcr.io/$PROJECT_ID/petparadise-api'
