# Etapa de construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto y restaurar las dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto de los archivos del código fuente
COPY . ./

# Compilar la aplicación
RUN dotnet publish -c Release -o out

# Etapa de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app
EXPOSE 8080

# Copiar el archivo publicado desde la etapa anterior
COPY --from=build /app/out .

# Definir el comando para ejecutar la aplicación
ENTRYPOINT ["dotnet", "PetParadiseAPI.dll"]
